name: Data Pipeline

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"

permissions:
  contents: write

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        pip install pandas requests

    - name: Run pipeline
      env:
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        ONEDRIVE_USER: ${{ secrets.ONEDRIVE_USER }}
      run: python scripts/pipeline.py

    - name: Debug files
      run: ls -R

    - name: Commit dataset
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add *.csv
        git commit -m "Auto-update dataset" || echo "No changes"
        git push
